// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Models;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            IsActive = true,
                            Price = 60000m,
                            ProductName = "Iphone 14"
                        },
                        new
                        {
                            id = 2,
                            IsActive = false,
                            Price = 50000m,
                            ProductName = "Iphone 13"
                        },
                        new
                        {
                            id = 3,
                            IsActive = true,
                            Price = 40000m,
                            ProductName = "Iphone 12"
                        },
                        new
                        {
                            id = 4,
                            IsActive = false,
                            Price = 30000m,
                            ProductName = "Iphone 11"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
